on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kubertech.azurecr.io
        username: ${{ secrets.acr_kubertech_username }}
        password: ${{ secrets.acr_kubertech_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/api" -f  "api/Dockerfile" -t kubertech.azurecr.io/automationteste:${{ github.sha }} --label dockerfile-path=api/Dockerfile
        docker push kubertech.azurecr.io/automationteste:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_automationteste_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep automation-teste8a65 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace automation-teste8a65`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: automation-teste8a65
        container-registry-url: kubertech.azurecr.io
        container-registry-username: ${{ secrets.acr_kubertech_username }}
        container-registry-password: ${{ secrets.acr_kubertech_password }}
        secret-name: automationtedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: automation-teste8a65
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          kubertech.azurecr.io/automationteste:${{ github.sha }}
        imagepullsecrets: |
          automationtedockerauth
